# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
import numpy as np
arr1d = np.arange(11,21)
print("Array dimensions before conversion: ", arr1d.ndim)
print("Original array: ", arr1d)
print("____________________________________________________")
arr2d = arr1d.reshape(-1,5)
print("Array dimensions after conversion: ", arr2d.ndim)
print("1D array converted to 2D: \n", arr2d)

Array dimensions before conversion:  1
Original array:  [11 12 13 14 15 16 17 18 19 20]
____________________________________________________
Array dimensions after conversion:  2
1D array converted to 2D: 
 [[11 12 13 14 15]
 [16 17 18 19 20]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [21]:
arr1 = np.arange(10).reshape(-1, 5)
arr2 = np.ones(10).reshape(-1, 5)
print("Stacking arr1 and arr2 vertically")
np.vstack((arr1, arr2)).astype(int)

Stacking arr1 and arr2 vertically


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [22]:
arr3 = np.arange(10).reshape(-1, 5)
arr4 = np.ones(10).reshape(-1, 5)
print("Stacking arr3 and arr4 horizontally")
np.hstack((arr3, arr4)).astype(int)

Stacking arr3 and arr4 horizontally


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [26]:
x = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [34]:
x = np.arange(15).reshape((1, 1, 5, 3, 1, 1))
print("Dimensions of array: ", x.ndim)
print("Array after converting to one dimension:", x.flatten())

Dimensions of array:  6
Array after converting to one dimension: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [46]:
x = np.arange(15)
print("Dimension of array:", x.ndim)
print("original array:", x)
x = x.reshape(5,3)
print("Dimension of array after converting:", x.ndim)
x

Dimension of array: 1
original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dimension of array after converting: 2


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [56]:
x = np.arange(1,26)
x = x.reshape(5,5)
np.square(x).astype(int)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

## Question:8

### Create 5x6 an array and find the mean?

In [67]:
x = np.arange(1,31).reshape(5, 6)
print("Mean of array: ", x.mean())

Mean of array:  15.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [68]:
x.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [69]:
np.median(x)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [70]:
x.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [89]:
x = np.arange(16).reshape(4,4)
print("Actual Array:\n", x)
print("\nsum of diagonal elements: ", x.trace())

Actual Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

sum of diagonal elements:  30


## Question:13

### Find the determinant of the previous array in Q12?

In [93]:
np.linalg.det(x)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [100]:
x = np.arange(1,11)
print("Actual Array: ",x)
print("\n5th Percentile of Array: ",np.percentile(x, 5))
print("\n95th Percentile of Array: ",np.percentile(x, 95))

Actual Array:  [ 1  2  3  4  5  6  7  8  9 10]

5th Percentile of Array:  1.4500000000000002

95th Percentile of Array:  9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [112]:
x = np.arange(1, 16).reshape(3, 5)
# replace odd numbers with nan
x = np.where(x % 2 != 0, np.NaN, x)
print(x)
print("\n False are the null values:\n\n",np.isnan(x))

[[nan  2. nan  4. nan]
 [ 6. nan  8. nan 10.]
 [nan 12. nan 14. nan]]

 False are the null values:

 [[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
